### PR TITLE
WIP: update to julia 0.6

### PR DESCRIPTION
**Pull request by iblis17**
- [ ] test on julia 0.7
- [x] ~~address deprecated warning popped from `examples/echo.jl`~~
  *Update*: the depwarn is from it's dependency.

### CODE REVIEW

**Comment by erikedin** [comment]
Thanks a lot for this! As you may be able to tell, I haven't actively maintained this repository for a long time.

I'll happily accept all the changes you made. I also made some minor fixes to the tests, and they kind of ran, but they would probably need some maintenance. The problems were anyhow unrelated to your changes.

Now, I haven't been keeping up-to-date with Julia, and it looks like it's going through a lot of changes. How would you recommend that I merge this? Should I merge is straight to master, or should I create a 0.6 branch for these changes and merge that into master later?
I have no idea if anyone is actually using this.

**Comment by iblis17** [comment]
> Now, I haven't been keeping up-to-date with Julia, and it looks like it's going through a lot of changes. How would you recommend that I merge this? Should I merge is straight to master, or should I create a 0.6 branch for these changes and merge that into master later?
I have no idea if anyone is actually using this.

I will prefer merge your test cases fixes at first, tag a release X, then remind user of Julia 0.5/0.4 choose the release X.
Next, I can rebase my PR against master and work on it. Once this PR get merged, I think it's suitable to bump version again.

**Comment by iblis17** [comment]
I add some fixes although the runtest still failed. Please check it out.

**Comment by iblis17** [comment]
Is this expected?
```julia
Integration test
  > Receive two Hello messages, and one binary.
  > Reconnect the client
  > The client initiates closing handshake
  > Client is disconnected when no pongs are received
ERROR (unhandled task failure): InvalidStateException("Channel is closed.", :closed)
Stacktrace:
 [1] check_channel_state(::Channel{Tuple{Function,Array{Any,1}}}) at ./channels.jl:131
 [2] put!(::Channel{Tuple{Function,Array{Any,1}}}, ::Tuple{DandelionWebSockets.#handle,Array{DandelionWebSockets.SocketClosed,1}}) at ./channels.jl:261
 [3] do_reader(::FakeFrameStream, ::DandelionWebSockets.ClientLogicTaskProxy) at /home/iblis/.julia/v0.6/DandelionWebSockets/src/network.jl:28
 [4] (::DandelionWebSockets.##1#2{FakeFrameStream,DandelionWebSockets.ClientLogicTaskProxy})() at ./event.jl:73
  > Check that default callbacks do nothing
13 facts verified.
```

**Comment by iblis17** [comment]
seems test cases passed, but there are some stacktraces

**Comment by erikedin** [comment]
I'm intend to put work into this again. Sorry about leaving it half way done.

**Pull request merged**
